import { ThemeProvider } from '@acme/ui/provider/theme-provider';
import { Toaster } from '@acme/ui/sonner';
import { siteName } from '@acme/white-label/web-app';
import type { Metadata } from 'next';
import { Ubuntu, Ubuntu_Mono } from 'next/font/google';
import { headers } from 'next/headers';
import { cookieToInitialState } from 'wagmi';
import AppLayout from '~/_components/layout/AppLayout';
import { ReactQueryProvider } from '~/_components/providers/ReactQueryProvider';
import { WagmiProvider } from '~/_components/providers/WagmiProvider';
import { getConfig } from '~/_config/wagmi';
import './globals.css';

const geistSans = Ubuntu({
  variable: '--font-ubuntu-sans',
  subsets: ['latin'],
  weight: ['300', '400', '500'],
});

const geistMono = Ubuntu_Mono({
  variable: '--font-ubuntu-mono',
  subsets: ['latin'],
  weight: ['400', '700'],
});

export const metadata: Metadata = {
  title: siteName,
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const wagmiInitialState = cookieToInitialState(getConfig(), (await headers()).get('cookie'));

  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <WagmiProvider initialState={wagmiInitialState}>
          <ReactQueryProvider>
            <ThemeProvider attribute="class" defaultTheme="system" enableSystem disableTransitionOnChange>
              <AppLayout>
                <Toaster />
                {children}
              </AppLayout>
            </ThemeProvider>
          </ReactQueryProvider>
        </WagmiProvider>
      </body>
    </html>
  );
}
